/icp_registration:
  ros__parameters:
    use_sim_time: false 
    rough_leaf_size: 1.0
    refine_leaf_size: 0.4
    pcd_path: ""
    map_frame_id: "map"
    odom_frame_id: "odom"
    range_odom_frame_id: "lidar_odom"
    laser_frame_id: "livox_frame"
    pointcloud_topic: "/livox/lidar/pointcloud"
    thresh: 0.3
    xy_offset: 3.0
    yaw_offset: 90.0
    yaw_resolution: 5.0
    initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, -90.0] # x,y,z,roll,pitch,yaw
