[package]
name = "ma_behavior_tree"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bonsai-bt = {version = "0.10.0", features = ["visualize"]}
r2r.workspace = true
serde = { version = "1.0", features = ["derive"] }
tokio = {workspace = true, features = ["sync", "time"]}
env_logger = "0.11"
log = "0.4"
tokio-stream = "0.1.17"

[[bin]]
name = "ma_bt"
path = "src/main.rs"
