image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1762.07212,    0.     ,  736.90955,
            0.     , 1754.3722 ,  577.86154,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.110612, 0.278337, -0.002006, 0.000554, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1747.03308,    0.     ,  736.73536,    0.     ,
            0.     , 1739.65125,  576.52946,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]